# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import stanzforms.models


class Migration(migrations.Migration):

    dependencies = [
        ('stanzforms', '0005_auto_20150810_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doska',
            name='articul',
            field=models.CharField(max_length=20, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='doska',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technologichka.Contractor', verbose_name='Изготовитель'),
        ),
        migrations.AlterField(
            model_name='doska',
            name='customer',
            field=models.TextField(blank=True, help_text='Кто платил, или типичные заказчики.', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='doska',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='doska',
            name='doska',
            field=models.ImageField(blank=True, help_text='Изображение доски', null=True, upload_to=stanzforms.models.get_doska_file_path, verbose_name='Доска'),
        ),
        migrations.AlterField(
            model_name='doska',
            name='maintenance',
            field=models.TextField(blank=True, help_text='Тут должны быть описаны любые работы, проведенные с доской.', verbose_name='Обслуживание'),
        ),
        migrations.AlterField(
            model_name='doska',
            name='make_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата изг.'),
        ),
        migrations.AlterField(
            model_name='doska',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='doska',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость, уе.'),
        ),
        migrations.AlterField(
            model_name='doska',
            name='spusk',
            field=models.ImageField(blank=True, help_text='Изображение печатного листа', null=True, upload_to=stanzforms.models.get_spusk_file_path, verbose_name='Спуск'),
        ),
        migrations.AlterField(
            model_name='knife',
            name='drawing',
            field=models.FileField(blank=True, help_text='Файл чертежа (PDF)', null=True, upload_to=stanzforms.models.get_drawing_file_path, verbose_name='Чертеж, PDF'),
        ),
        migrations.AlterField(
            model_name='knife',
            name='gabarit_a',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Габарит ширина', null=True),
        ),
        migrations.AlterField(
            model_name='knife',
            name='gabarit_b',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Габарит высота', null=True),
        ),
        migrations.AlterField(
            model_name='knife',
            name='gabarit_c',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Габарит глубина', null=True),
        ),
        migrations.AlterField(
            model_name='knife',
            name='knife',
            field=models.ImageField(blank=True, help_text='Изображение ножа', null=True, upload_to=stanzforms.models.get_knife_file_path, verbose_name='Нож, изобр.'),
        ),
        migrations.AlterField(
            model_name='knife',
            name='razvertka_h',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Развертка, высота', null=True),
        ),
        migrations.AlterField(
            model_name='knife',
            name='razvertka_w',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Развертка, ширина', null=True),
        ),
    ]
