# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stanzforms', '0006_auto_20170406_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doska',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Contractor', verbose_name='Изготовитель'),
        ),
    ]
