---
- name: frontail start as systemd service
  template: >
    src=frontail.service.j2
    dest=/etc/systemd/system/{{frontail_service}}
    mode=0644
    owner=root
    group=root
  notify:
  - restart frontail
  become: yes


