#
# Quick deploy - only fetch source code
#


---
- hosts: all
  gather_facts: no
  vars_files:
    - group_vars/vault.yml
  vars:
    branch: python3 # Choose branch for deploy


#
# TODO
# Копировать на удаленный сервер файл vault при каждом деплое
#

  tasks:

    - name: Check target
      fail:
        msg: "Deploy cant'n perform on development machine"
      when: group_names[0]=='development'

    #    - shell: whoami
    #      register: who
    #
    #    - debug: var=who.stdout
    #
    #    - fail: msg='stop'

    #
    # Remove old source code and virtual env
    #
    - name: Remove source code
      file:
        path: "{{ project_root }}"
        state: absent


    #
    # Get source code from github
    #
    - name: Fetch source code
      git:
        repo: "{{ project_repo }}"
        dest: "{{ project_root }}"
        version: "{{ branch }}"

    - name: Copy secret settings
      template:
        src: roles/django/templates/settings.env.j2
        dest: "{{project_root}}/.env"
        force: yes

    #
    # Migrate
    #
    - name: Django migrate
      django_manage:
        command: migrate
        app_path: "{{ project_root }}"
        virtualenv: "{{ virtualenv }}"


    #
    # Make timestamp of last deploy
    #
    - name: Make timestamp of deploy
      shell: echo `date +"%H:%m %d.%m.%Y"` > {{project_root}}/timestamp


    #
    # Restart rq worker
    #
    - name: Restart worker
      service:
        name: rqworker.service
        state: restarted
      become: yes