---
- hosts: all
  vars_files:
    - group_vars/secret_vars.yml

  roles:
    - system
    - backup
    - pdf
    - python
    - git
    - smsc
    - nginx
    - redis
    - postgres
    - hotfolder
    - pip
    - bower
    - django
    - uwsgi
