---

- hosts: all
  remote_user: "{{remote_user}}"
  vars_files:
    - credentials.yml
  #gather_facts: yes

  roles:
    - tty
    - python
    - git
    - smsc
    - nginx
    - redis
    - hotfolder
    - pip
    - bower
    - django
    - uwsgi
