---
- hosts: all
  vars_files:
    - group_vars/vault.yml

  roles:
    - system
    - cron-backup
    - pdf-utils
    - git
    - get-source
    - smsc
    - nginx
    - redis
    - postgres
    - hotfolder
    - npm
    - django
    - uwsgi
    - dotfiles
