---

# Steps to reproduce new server:
# - install fresh ubuntu machine on ESXi (testing on 15.04). During install select `OpenSSH Server`.
# - Write down custom ssh port to /etc/ssh/sshd-config
# - Assign appropriate static IP in winbox for new machine
# - Reboot
# - On machine, when run ansible: ssh-copy-id [user]@[server-ip] -p [server-port]
# - Note: Provision assumes, that pdfupload machine is dedicated server, so python package will install system-wide.
#         This is due high load on file system during pdf processing.


# Steps to recreate local development environment
# - install pycharm, git for windows, virtualbox, vagrant with ubuntu/vivid64
# - run `vagrant box add ubuntu/vivid64`
# - start pycharm
# - click 'Check out from version control', then Github
# - select appropriate repo and click 'Clone'
# - start vagrant box (tools -> vagrant -> up). This set-up environment with all dependencies.

# - add string to your hosts file: [vagrant-box-ip] vagrant.tes.pp.ua
# - vault magic word hint: b-0


- hosts: all
  remote_user: "{{remote_user}}"
  vars_files:
    - credentials.yml
  #gather_facts: yes

  roles:
    - tty
    - python
    - git
    - smsc
    - nginx
    - redis
    - hotfolder
    - pip
    - bower
    - django
    - uwsgi
