---
- hosts: all
  vars_files:
    - group_vars/vault.yml

  roles:
#    - system
#    - cron-backup
#    - pdf-utils
#    - python
#    - git
#    - get-source
#    - smsc
#    - nginx
#    - redis
    - postgres
#    - hotfolder
#    - pip
#    - npm
#    - django
#    - uwsgi
