---
- hosts: all
  vars_files:
    - group_vars/vault.yml

  roles:
    - system
    - dbbackup
    - project
    - smsc
    - redis
    - postgres
    - hotfolder
    - npm
    - django
    - gunicorn
    - nginx
    - rq
    - frontail
    - dotfiles