---
- hosts: all
  gather_facts: yes
  vars_files:
    - group_vars/vault.yml

  tasks:

    - name: drop db
      postgresql_db: >
        name={{db_name}}
        state=absent
      become: yes
      become_user: postgres

    - name: create db
      postgresql_db: >
        name={{ db_name }}
        encoding='UTF-8'
        lc_collate='en_US.UTF-8'
        lc_ctype='en_US.UTF-8'
        template='template0'
        state=present
      become: yes
      become_user: postgres

    - name: Ensure user has access to the database
      postgresql_user: >
        db={{ db_name }}
        name={{ db_user }}
        password={{ db_password }}
        priv=ALL
        state=present
      become: yes
      become_user: postgres

    - name: Ensure user does not have unnecessary privileges
      postgresql_user: >
        name={{ db_user }}
        role_attr_flags=NOSUPERUSER,NOCREATEDB
        state=present
      become: yes
      become_user: postgres

    - name: Determine latest backup filename
      local_action: shell ssh backup ls -rt /home/swasher/pdfupload | tail -1
      register: latest_backup

    - debug: msg={{latest_backup.stdout_lines}}

    - name: Copy postgres database
      shell: ssh backup cat /home/swasher/pdfupload/{{latest_backup.stdout_lines[0]}} | psql {{db_name}} -U {{db_user}}