---
- name: Remove default nginx site.
  #notify: restart nginx
  file: >
    path=/etc/nginx/sites-enabled/default
    state=absent
  become: yes


- name: Install nginx configuration file
  template: >
    src=nginx.conf.gunicorn.j2
    dest=/etc/nginx/sites-available/{{project_name}}
  become: yes


- name: Enable virtual host
  notify: restart nginx
  file: >
    src=/etc/nginx/sites-available/{{project_name}}
    dest=/etc/nginx/sites-enabled/{{project_name}}
    state=link
  become: yes
