# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 16:23
from __future__ import unicode_literals
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer'),
        ('technologichka', '0010_auto_20170620_1630'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Организация')),
                ('produce', models.CharField(blank=True, choices=[('ctp', 'Формы'), ('kli', 'Клише'), ('sta', 'Штанцы'), ('all', 'Разное')], max_length=3, null=True, verbose_name='Производство')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('remarks', models.TextField(blank=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name_plural': 'Подрядчики',
                'verbose_name': 'Подрядчик',
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]