---
- name: Install nginx system packages.
  apt: >
    pkg={{item}}
    state=installed
    update-cache=yes
    cache_valid_time={{ apt_cache_valid_time }}
  with_items:
    - redis-server
  sudo: yes
