---
- name: Install python
  apt: >
    pkg={{item}}
    state=installed
    update-cache=yes
    cache_valid_time={{ apt_cache_valid_time }}
  with_items:
    - python
    - python2.7-dev
    - libpython2.7-dev
    - libyaml-dev
  become: yes
