---
- name: Create required dir
  file: >
    path={{user_home}}/static_root/jpg
    state=directory


- name: Collecting static
  django_manage: >
    command=collectstatic
    app_path={{project_root}}