---
- name: Create required dir
  file: >
    path={{user_home}}/static_root
    state=directory


- name: Collecting static
  django_manage: >
    command="collectstatic --noinput --verbosity 0"
    app_path={{project_root}}