---
# DEPRECATED
# do not need make migration here: migrations alreade exists with source code
#
#- name: Django makemigration
#  # NOTE embedded ansible command dont work
#  django_manage: >
#    command=makemigrations
#    app_path={{project_root}}



# ansible bug [https://github.com/ansible/ansible/issues/15443]
# ./manage.py fail with permission error due to manage.py is not executable
# so we use second version without django_migrate till bug fix

#- name: migrate
#  django_manage: >
#    command=migrate
#    app_path={{project_root}}

- name: migrate
  shell: python manage.py migrate
  args:
    chdir: "{{ project_root }}"
