---
- name: Django makemigration
  # NOTE embedded ansible command dont work
  django_manage: >
    command=makemigrations
    app_path={{project_root}}
#  shell: 'python manage.py makemigrations'
#  args:
#    chdir: "{{project_root}}"

- name: Django migrate
  django_manage: >
    command=migrate
    app_path={{project_root}}