---

# This yaml setting up enveronment variable on target machine
# via systemd service, so after reboot variable will be actual.
# This variable using in django's setting.py for determine type
# of machine: production, staging or develop

# Also, it involves the use strictly names of Ansible groups:
# - production
# - staging
# - develop

- name: Set server type at boot time
  lineinfile: >
    dest=/etc/environment
    line={{environment_variable}}="{{group_names[0]}}"
  sudo: yes

- name: Set server type right now
  #shell: "set up ${{environment_variable}}"
  #environment:
  #  - '{{environment_variable}}': '{{group_names[0]}}'
  shell: "export {{environment_variable}}={{group_names[0]}}"

- name: Echo my_env_var again
  shell: "echo ${{environment_variable}}"