---

#
# This role install samba, create hotfolder directory, install incron, and setup incron settings
#

- include: samba.yml
- include: hotfolder.yml
- include: tmp_for_moving_files.yml
- include: inotify.yml



