---
- name: Install samba
  apt: >
    pkg={{item}}
    state=installed
    update-cache=yes
    cache_valid_time={{ apt_cache_valid_time }}
  with_items:
    - samba
  notify: restart samba
  become: yes

- name: Copy samba share template
  template: >
    src=samba.ini.j2
    dest={{samba_include}}
  become: yes

- name: Include template
  lineinfile: dest=/etc/samba/smb.conf
              line='include = {{samba_include}}'
  notify: restart samba
  become: yes

- name: Samba conf global
  blockinfile:
    dest: /etc/samba/smb.conf
    block: |
      preferred master = no
      domain master = no
      os level = 1
      local master = no
    insertafter: "## Browsing/Identification ###"
  notify: restart samba
  become: yes

- name: Change workgroup
  replace: dest=/etc/samba/smb.conf
           regexp='(\s+workgroup = )\w+(\n)'
           replace='\1{{workgroup}}\2'
  notify: restart samba
  become: yes