---
- name: Check OS support
  debug: >
    msg="The following OS distribution {{ ansible_distribution }} {{ ansible_lsb.major_release }} is not supported"
    fail=yes
  when: not ((ansible_distribution == 'Ubuntu' and ansible_lsb.major_release|int >= 15)
        or (ansible_distribution == 'Debian' and ansible_lsb.major_release|int >= 8))
