---

- name: Ensure .ssh dir exist
  file: >
    path=/home/{{remote_user}}/.ssh
    state=directory


- name: Copy .config
  template: >
    src=ssh_config.j2
    dest=/home/{{remote_user}}/.ssh/config
    owner={{remote_user}}
    group={{remote_user}}
    mode=0600
  become: yes

- name: Ensure machines will resolve his names
  lineinfile: >
    dest=/etc/hosts
    line="{{item.ip}} {{item.name}}"
  with_items: "{{servers}}"
  become: yes