---
# Ubuntu 16.10 have legacy one-byte locale en_US ISO-8859-1 (formely Latin 1).
# It mess MC special symbols
# This set en_US.UTF-8 as default locale

- name: Remove unnecesssary locale
  locale_gen:
    name: en_US
    state: absent
  become: yes

- name: Set LANGUAGE variable
  lineinfile:
    path: /etc/default/locale
    line: LANGUAGE="{{locale}}"
  become: yes

- name: Set LANGUAGE variable
  lineinfile:
    path: /etc/default/locale
    line: LC_ALL="{{locale}}"
  become: yes

- locale_gen:
    name: "{{locale}}"
    state: present
  become: yes