---
- debug: msg="Variable USER is {{ lookup('env','USER') }}"
- debug: msg="Variable HOME is {{ lookup('env','HOME') }}"


- debug: msg="USER HOME is {{user_home}}"
- debug: msg="PROJECT ROOT is {{project_root}}"
- debug: msg="remote_user is {{remote_user}}"
- debug: msg="ansible_ssh_user is {{ansible_ssh_user}}"


- debug: msg="hostvars is {{hostvars}}"
- debug: msg="group_names is {{group_names}}"
- debug: msg="groups is {{groups}}"
- debug: msg="inventory_hostname is {{inventory_hostname}}"
- debug: msg="play_hosts is {{play_hosts}}"



- name: for test purpose
  debug: msg="Empty action with vagrant_skip tag"
  tags: vagrant_skip

- fail: msg="Halt due testing purpose."