---
- debug: msg="Environment variable USER is {{ lookup('env','USER') }}"
- debug: msg="Environment variable HOME is {{ lookup('env','HOME') }}"

- debug: msg="USER HOME is {{user_home}}"
- debug: msg="PROJECT ROOT is {{project_root}}"
- debug: msg="remote_user is {{remote_user}}"
- debug: msg="ansible_ssh_user is {{ansible_ssh_user}}"

#- debug: msg="test_var is {{test_var}}"
- debug: msg="smsc_login is {{smsc_login}}"
- debug: msg="smsc_password is {{smsc_password}}"
- debug: msg="secret_key is {{secret_key}}"
- debug: msg="passphrase is {{passphrase}}"
- debug: msg="superusername is {{superusername}}"
- debug: msg="superuserpassword is {{superuserpassword}}"
- debug: msg="superuseremail is {{superuseremail}}"
#- debug: msg="vartest is {{vartest}}"

- fail: msg="Halt due testing purpose."

#- debug: msg="hostvars is {{hostvars}}"
- debug: msg="groups.all is {{groups['all']}}"
- debug: msg="play_hosts is {{play_hosts}}"
- debug: msg="group_names is {{group_names}}"
- debug: msg="group_names[0] is {{group_names[0]}}"
- debug: msg="groups is {{groups}}"
- debug: msg="inventory_hostname is {{inventory_hostname}}"
- debug: msg="play_hosts is {{play_hosts}}"

- name: for test purpose
  debug: msg="Empty action with vagrant_skip tag"
  tags: vagrant_skip

- name: test delegating
  shell: ifconfig
  delegate_to: production
  register: ifconfig

- debug: var=ifconfig.stdout_lines

- debug: msg="Prodiction IP is {{groups.production}}"

- fail: msg="Halt due testing purpose."



# samba
#msg: Failed to start samba.service: Unit samba.service is masked.

# smb
#msg: Failed to stop smb.service: Unit smb.service not loaded.
#Failed to start smb.service: Unit smb.service failed to load: No such file or directory.

#samba.service
#msg: Failed to start samba.service: Unit samba.service is masked.

#smbd.service
# OKEY