# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-14 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technologichka', '0003_auto_20150807_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='name',
            field=models.ForeignKey(help_text=b'', on_delete=django.db.models.deletion.CASCADE, to='technologichka.OperationList', verbose_name=b'\xd0\x9e\xd0\xbf\xd0\xb5\xd1\x80\xd0\xb0\xd1\x86\xd0\xb8\xd1\x8f'),
        ),
    ]
