# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technologichka', '0004_auto_20160714_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='produce',
            field=models.CharField(blank=True, choices=[('ctp', 'Формы'), ('kli', 'Клише'), ('sta', 'Штанцы'), ('all', 'Разное')], max_length=3, null=True, verbose_name='Производство'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fio',
            field=models.CharField(blank=True, help_text='ФИО и должность контактного лица', max_length=150, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, help_text='Телефон контактного лица', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='detal',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Тираж'),
        ),
        migrations.AlterField(
            model_name='detal',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название детали'),
        ),
        migrations.AlterField(
            model_name='detal',
            name='size',
            field=models.CharField(blank=True, max_length=20, verbose_name='Размер, мм'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='technologichka.Contractor', verbose_name='Подрядчик'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technologichka.OperationList', verbose_name='Операция'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость, грн.'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='printsheet',
            field=models.ForeignKey(blank=True, help_text='Если оперция не относится к конкретному печатному листу, оставьте это поле пустым', null=True, on_delete=django.db.models.deletion.CASCADE, to='technologichka.PrintSheet', verbose_name='Печатный лист'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technologichka.Customer', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(blank=True, help_text='Предполагаемая дата сдачи заказа', null=True, verbose_name='Сдать до'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_production',
            field=models.BooleanField(default=True, help_text='Заказ находится в производстве'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.IntegerField(help_text='Max order', unique=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость, грн.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(help_text='Общее кол-во заказанных изделий', verbose_name='Тираж'),
        ),
        migrations.AlterField(
            model_name='order',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='Описание заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateField(help_text='Дата оформления заказа', verbose_name='Дата оформления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_ready',
            field=models.BooleanField(default=False, help_text='True когда заказ готов к выдаче заказчику.'),
        ),
        migrations.AlterField(
            model_name='printsheet',
            name='colors',
            field=models.CharField(blank=True, max_length=10, verbose_name='Цветность'),
        ),
        migrations.AlterField(
            model_name='printsheet',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название листа'),
        ),
        migrations.AlterField(
            model_name='printsheet',
            name='outputter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='technologichka.Contractor', verbose_name='Вывод пластин'),
        ),
        migrations.AlterField(
            model_name='printsheet',
            name='paper',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Граммаж и тип бумаги'),
        ),
        migrations.AlterField(
            model_name='printsheet',
            name='paper_printing_amount',
            field=models.CharField(blank=True, help_text='Общее кол-во выданных листов', max_length=20, verbose_name='Печать, кол-во'),
        ),
        migrations.AlterField(
            model_name='printsheet',
            name='paper_printing_format',
            field=models.CharField(blank=True, help_text='Формат бумаги в печать', max_length=20, verbose_name='Печать, ф-т'),
        ),
        migrations.AlterField(
            model_name='printsheet',
            name='paper_warehouse_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Количество единиц, выданных со склада', max_digits=12, null=True, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='printsheet',
            name='paper_warehouse_format',
            field=models.CharField(blank=True, help_text='Формат размотки ИЛИ формат листовой бумаги', max_length=20, verbose_name='Ф-т размотки'),
        ),
        migrations.AlterField(
            model_name='printsheet',
            name='paper_warehouse_unit',
            field=models.CharField(blank=True, choices=[('leaf', 'Листы'), ('kg', 'Кг')], help_text='Единица бумаги (СКЛАД)', max_length=4, null=True, verbose_name='Ед.:'),
        ),
        migrations.AlterField(
            model_name='printsheet',
            name='plates',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Кол-во пластин на один лист', null=True, verbose_name='Пластины'),
        ),
        migrations.AlterField(
            model_name='printsheet',
            name='pressrun',
            field=models.IntegerField(blank=True, help_text='Технологический тираж одного листа', null=True, verbose_name='Тираж'),
        ),
        migrations.AlterField(
            model_name='printsheet',
            name='printingpress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.PrintingPress', verbose_name='Печатная машина'),
        ),
        migrations.AlterField(
            model_name='printsheet',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Кол-во одинаковых печатных листов', null=True, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='printsheet',
            name='turnover',
            field=models.CharField(blank=True, choices=[('SingleSide', 'Без оборота'), ('WorkAndTurn', 'Свой оборот'), ('WorkAndThumble', 'Хвост-на-голову'), ('Perfecting', 'Чужой оборот')], max_length=20, null=True, verbose_name='Оборот'),
        ),
    ]
