# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologichka', '0005_auto_20170406_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='allow_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='unc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
