# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technologichka', '0007_auto_20170620_1119'),
        ('core', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Customer', verbose_name='Заказчик'),
        ),
    ]
