# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technologichka', '0009_auto_20170620_1131'),
    ]

    database_operations = [
        migrations.AlterModelTable('Contractor', 'core_contractor')
    ]

    state_operations = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]