# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stanzforms', '0007_auto_20170620_1623'),
        ('technologichka', '0010_auto_20170620_1630'),
        ('core', '0003_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Contractor', verbose_name='Подрядчик'),
        ),
        migrations.AlterField(
            model_name='printsheet',
            name='outputter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Contractor', verbose_name='Вывод пластин'),
        ),
    ]
