# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technologichka', '0011_auto_20170620_1623'),
    ]

    state_operations = [
        migrations.DeleteModel(
            name='Contractor',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]