---
- name: Ensure log directory present
  file: >
    dest={{log_dir}}
    state=directory


- name: Install uwsgi
  pip: >
    name=uwsgi
    state=latest
    extra_args='--quiet'
  become: yes


- name: Making sure uwsgi config directories are there
  file: path=/etc/{{ item }} state=directory mode=0755
  with_items:
    - uwsgi
    - uwsgi/vassals
  become: yes


- name: Copy emperor template
  template: >
    src=emperor.ini.j2
    dest=/etc/uwsgi/emperor.ini
    mode=0644
    owner=root
    group=root
  become: yes


# FOR UPSTART
#- name: Setup upstart job for the emperor NOT TESTING - MAY NOT WORK
#  copy: src=upstart.conf dest=/etc/init/uwsgi.conf mode=0644 owner=root group=root
#  become: yes


- name: Setup systemd SERVICE file for the emperor
  copy: src=systemd.service dest=/etc/systemd/system/{{emperor_service}} mode=0644 owner=root group=root
  when: >
      (ansible_distribution == 'Ubuntu' and ansible_lsb.major_release|int >= 15)
      or (ansible_distribution == 'Debian' and ansible_lsb.major_release|int >= 8)
  become: yes

- name: Setup systemd SOCKET file for the emperor
  template: src=systemd.socket dest=/etc/systemd/system/{{emperor_socket}} mode=0644 owner=root group=root
  when: >
      (ansible_distribution == 'Ubuntu' and ansible_lsb.major_release|int >= 15)
      or (ansible_distribution == 'Debian' and ansible_lsb.major_release|int >= 8)
  become: yes
