---
- name: Ensure log directory present
  file: >
    dest={{log_dir}}
    state=directory


- name: Install uwsgi
  pip: >
    name=uwsgi
    state=latest
    extra_args='--quiet'
  become: yes


- name: Make sure if uwsgi config directories is there
  file: path=/etc/{{ item }} state=directory mode=0755
  with_items:
    - uwsgi
    - uwsgi/vassals
  become: yes


- name: Copy emperor template
  template: >
    src=emperor.ini.j2
    dest=/etc/uwsgi/emperor.ini
    mode=0644
    owner=root
    group=root
  become: yes


- name: Setup systemd SERVICE file for the emperor
  copy: src=systemd.service dest=/etc/systemd/system/{{emperor_service}} mode=0644 owner=root group=root
  become: yes

- name: Setup systemd SOCKET file for the emperor
  template: src=systemd.socket dest=/etc/systemd/system/{{emperor_socket}} mode=0644 owner=root group=root
  become: yes
