---

#
# On a modern system, /run/ is mounted as a tmpfs and is the right place to put sockets and pidfiles into.
#

- name: Make systemd-tmpfiles, which create /run/uwsgi at each boot
  template: >
    src=tmpfiles.d.j2
    dest=/etc/tmpfiles.d/{{tmpfilesd_template}}
    mode=0600
    owner=root
    group=root
  become: yes


- name: Create tmpdir right now
  shell: systemd-tmpfiles --create {{tmpfilesd_template}}
  args:
    chdir: /etc/tmpfiles.d
  become: yes