---
#- name: Stop uwsgi.service
#  service: >
#    name={{emperor_service}}
#    state=stopped
#  become: yes
#
#- name: Start uwsgi.socket
#  service: >
#    name={{emperor_socket}}
#    state=started
#  become: yes

- name: Start uwsgi.service
  service: >
    name={{emperor_service}}
    state=started
  become: yes


# As described in manual,
# - Then disable the service and enable the socket unit.
# - systemctl disable emperor.uwsgi.service
# - systemctl enable emperor.uwsgi.socket
# ---- Я так понял, что при загрузке должен стартовать только сокет, а он уже поднимает сервис, когда в сокет обращаются

- name: Start uwsgi.service
  service: >
    name={{emperor_service}}
    enabled=no
  become: yes

- name: Start uwsgi.socket
  service: >
    name={{emperor_socket}}
    enabled=yes
  become: yes

# finally, restart nginx
- name: Restart nginx
  service: >
    name=nginx
    state=restarted
  become: yes