---
- name: Install poppler-utils(pdfinfo), ghostscript
  apt: >
    pkg={{item}}
    state=installed
    update-cache=yes
    cache_valid_time={{ apt_cache_valid_time }}
  with_items:
    - poppler-utils
    - ghostscript
    # deprecated: pdfcrop.pl no more using
    #- texlive-binaries  # for pdfcrop.pl
  become: yes