---
- name: Install pypy binary dependencies
  apt:
    pkg: "{{item}}"
    state: installed
    update-cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"
  with_items:
    - python3
    - python3-dev
    - python3-venv
    - libyaml-dev
    - python-psycopg2
    - python3-dev
    - libjpeg-dev  #for pillow
    - libpq-dev    #for psycopg2
  become: yes

