---
- name: Install poppler-utils, which contains pdfinfo tool.
  apt: >
    pkg={{item}}
    state=installed
    update-cache=yes
    cache_valid_time={{ apt_cache_valid_time }}
  with_items:
    - poppler-utils
  sudo: yes