# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_ftp_passive_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ftp',
            options={'verbose_name': '\u0424\u0422\u041f', 'verbose_name_plural': '\u0424\u0422\u041f'},
        ),
    ]
