# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 15:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0006_auto_20160407_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('telegram_id', models.IntegerField(blank=True, null=True)),
                ('telegram_notify', models.BooleanField(default=False)),
                ('sms_notify', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='outputter',
            name='sms_receiver',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
