# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_auto_20160422_1554'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Outputter',
            new_name='Ctpbureau',
        ),
        migrations.AlterModelOptions(
            name='ctpbureau',
            options={'verbose_name': 'CTP \u0431\u044e\u0440\u043e', 'verbose_name_plural': 'CTP \u0431\u044e\u0440\u043e'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': '\u0421\u043e\u0442\u0440\u0443\u0434\u043d\u0438\u043a', 'verbose_name_plural': '\u0421\u043e\u0442\u0440\u0443\u0434\u043d\u0438\u043a\u0438'},
        ),
        migrations.AlterModelOptions(
            name='grid',
            options={'verbose_name': '\u0417\u0430\u043b\u0438\u0432\u043a\u0430', 'verbose_name_plural': '\u0417\u0430\u043b\u0438\u0432\u043a\u0438'},
        ),
    ]
