# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-21 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_auto_20160425_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grid',
            options={'verbose_name': '\u0417\u0430\u043b\u0438\u0442\u044b\u0439 \u0444\u0430\u0439\u043b', 'verbose_name_plural': '\u0417\u0430\u043b\u0438\u0442\u044b\u0435 \u0444\u0430\u0439\u043b\u044b'},
        ),
    ]
