# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_auto_20160921_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='grid',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='printingpress',
            name='cost',
            field=models.IntegerField(blank=True, help_text='Cost of one plate', null=True),
        ),
        migrations.AlterField(
            model_name='printingpress',
            name='klapan',
            field=models.IntegerField(help_text='Расстояние от нижнего края пластины до края бумаги', verbose_name='Клапан'),
        ),
        migrations.AlterField(
            model_name='printingpress',
            name='name',
            field=models.CharField(help_text='Название печатного пресса', max_length=150, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='printingpress',
            name='plate_h',
            field=models.IntegerField(verbose_name='Высота пластины, мм'),
        ),
        migrations.AlterField(
            model_name='printingpress',
            name='plate_w',
            field=models.IntegerField(verbose_name='Ширина пластины, мм'),
        ),
    ]
