# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_auto_20170406_1300'),
    ]

    database_operations = [
        migrations.AlterModelTable('Employee', 'core_employee')
    ]

    state_operations = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]