# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0012_auto_20170619_1435'),
    ]

    # This needs to be a state-only operation because the database model was
    # renamed, and no longer exists according to Django.
    state_operations = [
        # Pasted from auto-generated operations in previous step:
        migrations.DeleteModel(
            name='Employee',
        ),
    ]

    operations = [
        # After this state operation, the Django DB state should match the
        # actual database structure.
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]