# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_auto_20170619_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftp',
            name='todir',
            field=models.CharField(blank=True, default='', max_length=150),
            preserve_default=False,
        ),
    ]
