# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_auto_20170622_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Contractor'),
        ),
    ]
