# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0015_auto_20170629_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctpbureau',
            name='ftp_account',
        ),
        migrations.DeleteModel(
            name='Ctpbureau',
        ),
    ]
