# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technologichka', '0006_auto_20170617_1808'),
        ('stanzforms', '0006_auto_20170406_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_filename', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=150)),
                ('last_change', models.DateField()),
                ('approved', models.BooleanField(help_text='Заказчик утвердил макет')),
                ('approved_date', models.DateField(help_text='Дата утверждения')),
                ('thumb', models.ImageField(upload_to='')),
                ('preview', models.ImageField(upload_to='')),
                ('size', models.CharField(max_length=20)),
                ('is_cutting', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technologichka.Customer')),
                ('knife', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stanzforms.Knife')),
            ],
        ),
    ]
